### ISSUE TITLE
[Bug] JSON dumps on plan for type changes

### ISSUE THREAD

**Issue by tim-steinkuhler** [dbt-labs/dbt-jobs-as-code#115]
**Describe the bug**
After implementing the solution to #113 (your speed is awesome by the way).

I reran my plan on the latest version, and ran into this error:

```
dbt-jobs-as-code plan ./dbt_jobs/preprod.yml --limit-projects-envs-to-yml

2024-12-11 09:06:08.598 | DEBUG    | dbt_jobs_as_code.client:_build_parameters:233 - Request parameters {'offset': 0, 'project_id': 7328, 'environment_id': 15924}
2024-12-11 09:06:08.801 | INFO     | dbt_jobs_as_code.cloud_yaml_mapping.change_set:build_change_set:193 - Detected 3 existing jobs.
2024-12-11 09:06:08.801 | INFO     | dbt_jobs_as_code.cloud_yaml_mapping.change_set:build_change_set:195 - Checking for differences in build_state_modified
2024-12-11 09:06:08.803 | INFO     | dbt_jobs_as_code.schemas:check_job_mapping_same:45 - ❌ Job build_state_modified is different - Diff:
{
  "values_changed": {
    "root['name']": {
      "new_value": "preprod - build modified and downstream",
      "old_value": "Build preprod state:modified"
    },
    "root['schedule']['cron']": {
      "new_value": "0 3,8,12 * * 0,1,2,3,4,5,6",
      "old_value": "2 */12 * * 0,1,2,3,4,5,6"
    },
    "root['schedule']['date']['cron']": {
      "new_value": "0 3,8,12 * * 0,1,2,3,4,5,6",
      "old_value": "2 */12 * * 0,1,2,3,4,5,6"
    },
    "root['description']": {
      "new_value": "Execute when something is merged to main. Uses state:modified setting",
      "old_value": "Job to execute when something is merged to main. Uses state:modified setting"
    }
  }
}
2024-12-11 09:06:08.803 | INFO     | dbt_jobs_as_code.cloud_yaml_mapping.change_set:build_change_set:195 - Checking for differences in ci
2024-12-11 09:06:08.804 | INFO     | dbt_jobs_as_code.schemas:check_job_mapping_same:45 - ❌ Job ci is different - Diff:
{
  "values_changed": {
    "root['name']": {
      "new_value": "preprod - CI",
      "old_value": "CI Pre Production"
    },
    "root['schedule']['cron']": {
      "new_value": "0 3,8,12 * * 0,1,2,3,4,5,6",
      "old_value": "2 */12 * * 0,1,2,3,4,5,6"
    },
    "root['schedule']['date']['cron']": {
      "new_value": "0 3,8,12 * * 0,1,2,3,4,5,6",
      "old_value": "2 */12 * * 0,1,2,3,4,5,6"
    }
  }
}
2024-12-11 09:06:08.804 | INFO     | dbt_jobs_as_code.cloud_yaml_mapping.change_set:build_change_set:195 - Checking for differences in build
Traceback (most recent call last):
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/bin/dbt-jobs-as-code", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/dbt_jobs_as_code/main.py", line 159, in plan
    change_set = build_change_set(
                 ^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/dbt_jobs_as_code/cloud_yaml_mapping/change_set.py", line 196, in build_change_set
    if not check_job_mapping_same(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/repos/nibc/dbt-cloud-terraform/.venv/lib/python3.12/site-packages/dbt_jobs_as_code/schemas/__init__.py", line 46, in check_job_mapping_same
    f"❌ Job {source_job.identifier} is different - Diff:\n{json.dumps(diffs, indent=2)}"
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/Users/timsteinkuhler/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
```

Basically, the plan is working fine, unless there are "non-JSON serializable" objects.

This is the data for the example above:

```json
{
    "type_changes": {
        "root['deferring_job_definition_id']": {
            "old_type": "<class NoneType>",
            "new_type": "<class int>",
            "old_value": "None",
            "new_value": 243183
        },
        "root['deferring_environment_id']": {
            "old_type": "<class int>",
            "new_type": "<class NoneType>",
            "old_value": 15924,
            "new_value": "None"
        }
    },
    "values_changed": {
        "root['name']": {
            "new_value": "Build preprod",
            "old_value": "preprod - scheduled build"
        },
        "root['description']": {
            "new_value": "Scheduled job that builds preprod",
            "old_value": "Scheduled build job on preprod"
        }
    }
}
```

**To Reproduce**
1. Install v 1.0.0
2. For an existing job, remove a value that was set, or set a value that wasn't set before, resulting in a type change
3. run a plan

**Expected behavior**
I would expect a working plan :D.

**Desktop (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - dbt Core Version [e.g. 1.3.1]: - not relevant
 - `dbt-jobs-as-code` Version [e.g. 1.0.0]: 1.0.0

**Comment by b-per** [comment]
That's not good 😬

I am jumping on a call now but will do a quick bugfix today then and will add a test for this. For now, you can revert to the previous version if you are stuck.

**Comment by tim-steinkuhler** [comment]
That's awesome!

**Comment by b-per** [comment]
Thanks for the report. I have released the fix in 1.0.1 while still keeping the diff output as JSON formatted.
If there are more errors I might just try to `pprint` the dict but the output is less readable though.
